In [ ]:
# Массив - это упорядоченный набор, однотипных данных.


In [28]:
import numpy as np

arr = np.array([1,5,2,9,10]) # превращаем список, в Numpy массив.
arr

array([ 1,  5,  2,  9, 10])

In [31]:
print(type(arr)) # nd - n, мерный массив.

<class 'numpy.ndarray'>


In [32]:
nd_arr = np.array([ # создаем двумерный массив, 3 строки, 3 столба.
    [12, 45, 78],
    [34, 56, 13],
    [12, 98, 76]
])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [33]:
arr = np.array([1,5,2,9,10])
arr.dtype

dtype('int32')

In [34]:
arr = np.array([1,5,2,9,10], dtype=np.int8) # задаем еще тип данных который можно изменить.
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [35]:
arr[2] = 2000
arr.dtype
arr # как итог, 2000 были автоматически приведены к формату int8 и все то, что не влезло в отведенный объем памяти исчезло.

array([  1,   5, -48,   9,  10], dtype=int8)

In [36]:
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [37]:
arr[2] = '12' # передавая строку, это не вызовет ошибку, если к строке можно применить функцию int и в строке число. 
# К остальным не числовым значениям строк, нельзя задать функцию int.
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [42]:
arr = np.float64(arr)
arr

array([ 1.,  5., 12.,  9., 10.])

In [43]:
arr.dtype = np.int32()
arr

array([         0, 1072693248,          0, 1075052544,          0,
       1076363264,          0, 1075970048,          0, 1076101120])

In [44]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr

array([12321, -1234,  3435,  -214,   100])

In [46]:
arr = np.uint8(arr) # все числа что не сохранили свою размерность, оказались больше допустимых границ формата данных, так и стем что содержали формат -, т.к. в uint только положительные.
arr

array([ 33,  46, 107,  42, 100], dtype=uint8)

In [47]:
arr = np.array([1, 5, 2, 9, 10], dtype=np.int8)
nd_arr = np.array([
    [12, 45, 78],
    [34, 56, 13],
    [12, 98, 76],
    [43, 23, 78]
], dtype=np.int16)

In [48]:
arr.ndim # число размерности в массиве

1

In [49]:
nd_arr.ndim # число размерности в массиве

2

In [50]:
arr.size # кол-во элементов(чисел) в массиве

5

In [51]:
nd_arr.size # кол-во элементов(чисел) в массиве

12

In [52]:
arr.shape # форма массива, возвращает в виде кортежа

(5,)

In [56]:
nd_arr.shape # форма массива, возвращает в виде кортежа. Для двумерного - в начале "число строк '4'", далее "число столбов '3'".

(4, 3)

In [58]:
arr.itemsize # указывает на то, сколько байт памяти отведено под каждый элемент в массиве.

1

In [57]:
nd_arr.itemsize # указывает на то, сколько байт памяти отведено под каждый элемент в массиве.

2

In [59]:
zeros_id = np.zeros(5) # создаем одномерный массив с 5-ю числами 0.
zeros_id

array([0., 0., 0., 0., 0.])

In [62]:
zeros_3d = np.zeros((5, 4, 3), dtype=np.float32) # создаем массив, в котором 5 строк, 4 столбца и 3 таблички 5.4
print(zeros_3d.shape)
zeros_3d

(5, 4, 3)


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [78]:
np.arange(5) # эта функция cоздающая массив, в котором указанное число являеться правой границей для массива от 0 и до числа в скобка. Можно использовать не только целые числа 

array([0, 1, 2, 3, 4])

In [65]:
np.arange(2.5, 5) # можно передавать так-же дробные числа.

array([2.5, 3.5, 4.5])

In [66]:
np.arange(2.5, 5, 0.5) # 1 - число, это то, от которого идет исчесление, 2 - на котором заканчивают (не включительно), 3 - это шаг, с которым идут от и до прабавляя друг к другу.

array([2.5, 3. , 3.5, 4. , 4.5])

In [67]:
np.arange(2.5, 5, 0.5, dtype=np.float16) # можно задавать еще тип данных.

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [68]:
# numpy не советовать использовать дробные значения для шага. Для этого есть функция linspace.

In [72]:
arr = np.linspace(1, 2, 10) # 1 - число, это то с которого должен начинаться массив, 2 - число, это правая граница массива, 3 - число, это число элементов в массиве что мы хотим получить.
arr # итого, мы хотим получить 10-ть чисел в интервале от 1 до 2.

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [73]:
arr = np.linspace(1, 2, 10, endpoint=False) # с помощью аргумента endpoint - мы можем указать должен ли массив содержать последнее число или нет.
arr 

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [77]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)

0.1111111111111111


In [88]:
arr, step = np.linspace(-6, 21, 60, endpoint=True, retstep=True)
print(step)
round(step, 2)

0.4576271186440678


0.46

In [89]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(step)
round(step, 2)

0.45


0.45