In [21]:
import numpy as np

arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
arr.shape = (2, 4) # изменяем форму нашего одномерного массива на 2 строки, 4 столбца
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4)) # сохраняя прежний массив, передаем картеж и изменяем его размерность
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F') # изменяем принцип формы массива, order f - разбивает массив по столбцам, т.е. счет идет не в строчку а в столбец.
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [26]:
arr = np.arange(8)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [78]:
arr_trans = arr.transpose() # транспонируем изменяем размерность массива, переворачивая его, т.е. если было 2 строки и 4 столба, то transpose переворачивает в 4 строки и 2 столба.
arr_trans

array([ 3,  4, 12, 12, 15, 23, 23, 45])

In [29]:
arr = np.arange(3)
print(arr.shape)
arr_trans = arr.transpose()
print(arr_trans.shape)

(3,)
(3,)


In [30]:
arr = np.linspace(1, 2, 6) # cоздаем массив из 6 чисел, от 1 до 2.
arr 

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [31]:
print(arr[2])

1.4


In [35]:
print(arr[2:4]) # делаем срез, начальный элемент - входит в выборку, конечный - нет.

[1.4 1.6]


In [37]:
print(arr[::-1]) # разворачиваем срез массива

[2.  1.8 1.6 1.4 1.2 1. ]


In [38]:
nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [40]:
nd_array[1][2] # индексация по спискам, в квадратных скобках индексы.

3.0

In [42]:
nd_array[1, 2] # тоже самое. Только проще 1 индекс по первой размерности и 2 индекс по второй размерности.

3.0

In [44]:
nd_array[:2, 2] # находим строки ":" с 0 строки по 2 не включительно и только во 2 столбце. 

array([1., 3.])

In [46]:
nd_array[1:, 2:4] # можно найти по нескольким размерностям. Находим с 1 строки и все остальные, а по столбцам со 2 включительно и по 4 не включительно.

array([[3. , 3.5],
       [5. , 5.5]])

In [47]:
nd_array[:, 2:4] # если хотим взять все строки из массива то просто двоеточие и столбцы начиная со 2 включительно и по 4 не включительно.

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [49]:
nd_array[:2] # мы получаем срез строк с 0 по 1 включительно и всю информацию о всех столбцах.

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [51]:
arr = np.array([23, 12, 45, 12, 23, 4, 15, 3])

arr_new = np.sort(arr) # сортируем массив arr - сортировка по возростанию
print(arr)
print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [55]:
arr = np.array([23, 12, 45, 12, 23, 4, 15, 3])

print(arr.sort()) # ничего не вернула, но при этом будет отсортирован исходный массив.
print(arr)

None
[ 3  4 12 12 15 23 23 45]


In [56]:
data = np.array([4, 9, -4, 3])

In [62]:
roots = np.sqrt(data) # извлекаем квадратный корень из массива с помощью функции sqrt. Сохраняя все квадратные корни из всех элементов массива дата.
roots # + NumPy поругался на некорректный аргумент для функции sqrt, а именно отрицательное число, при этом квадратные корни из отрицательных чисел не берутся.
# корен для числа с ошибкой был сохранен в массиве как nan - это особый формат числа, который показывает отсутствие числа в NumPy(число формата float).

<ipython-input-62-a1fa22eaf180>:1: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data) # извлекаем квадратный корень из массива с помощью функции sqrt. Сохраняя все квадратные корни из всех элементов массива дата.


array([2.        , 3.        ,        nan, 1.73205081])

In [64]:
print(None == None) # Питоновские наны, равны друг другу.
print(np.nan == np.nan) # NumPy наны, не равны друг другу.

True
False


In [65]:
print(None is None) # можно сравнивать методом is, это рекомендованный метод сравнения нанов.
print(np.nan is np.nan)
print(np.nan is None)

True
True
False


In [67]:
sum(roots) # просумируем все числа в массиве, мы получаем nan - т.к. если складывать nan то на выходе будет nan.

nan

In [70]:
np.isnan(roots) # находим nan-ы в массиве. На выходе выдает булевый массив, где true == nan, false != nan.

array([False, False,  True, False])

In [73]:
roots[np.isnan(roots)] # функция isnan можно использовать в качестве индекса, для массива roots.

array([nan])

In [75]:
roots[np.isnan(roots)] = 0 # находим nan в нашем массиве и вместо nan проставляем везде 0.
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [79]:
sum(roots) # теперь можно спокойно суммировать.

6.732050807568877