In [2]:
import numpy as np

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

vec1 + vec2 # операции в Numpy происходят поэлементно от 0 и до крайнего правого.

array([14. , 10. , 10.6, 15.5])

In [4]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]

list1 + list2 # тут сложились два списка в котором, к элементам 1 прибавились элементы из 2.

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [6]:
[x + y for x, y in zip(list1, list2)] # тоже самое получили что и в первом только чуть сложнее.

[14, 10, 10.6, 15.5]

In [7]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

vec1 * vec2 # умножение тоже поэлементное

array([24. , 24. , 25.2, 32.5])

In [9]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6])

vec1 + vec2 # невозможно произвести перемножение у векторов разной длинны.

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [12]:
vec = np.arange(5) # другое дело перемножение вектора и единичного числа.
print(vec * 10)
print(vec ** 2)

[ 0 10 20 30 40]
[ 0  1  4  9 16]


In [13]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

vec1 > vec2 # сравнение вектора с вектором идет поэлементно

array([False, False,  True, False])

In [15]:
vec = np.array([14, 15, 9, 26, 53, 5, 89])
vec <= 26 # сравнение вектора с числом идет поэлементно, выдает массив из булевых переменных.

array([ True,  True,  True,  True, False,  True, False])

In [17]:
vec = np.array([3, 4]) 

In [18]:
lenght = np.sqrt(np.sum(vec ** 2)) # длинна вектора, это такая величина которая получаеться путём суммирования квадратов элементов вектора, 
# а затем извлечение из полученного числа квадратного корня
print(lenght)

5.0


In [23]:
lenght = np.linalg.norm(vec) # в NumPy есть упращенная форма поиска величины что выше. Функция линейной алгебры linalg и функции Nomr == тоже самое что его длинна.
print(lenght) # Длинна вектора в NumPy

5.0


In [24]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])

distance = np.sqrt(np.sum((vec1 - vec2) ** 2)) # считаем расстояние между векторами. Разность каждых координат возводят в квадрат и суммируют, а затем из суммы извлекают квадрат.
distance

12.206555615733702

In [26]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])

distance = np.linalg.norm(vec1 - vec2)
distance # расстояние между векторами в NumPy нужно взять функцию np.linalg.norm() для разности векторов vec1 - vec2

12.206555615733702

In [33]:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)

scalar_pro = np.sum(vec1 * vec2) # Скалярное произведение - сумма произведений элементов векторов.
scalar_pro

250.0

In [39]:
scalar_pro = np.dot(vec1, vec2) # Скалярное произведение в NumPy np.dot(первый, второй вектор)
scalar_pro
# Скалярное произведение, чеще всего используют для определения угла между двумя векторами.
# Если скалярное произведение = 0, это значит что вектора перпендикулярны, т.е. угол между векторами = 90 градусов.

250.0

In [40]:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y) # перпендикулярные вектора


0

In [46]:
vec = np.array([2, 7, 18, 28, 18, 1, 8, 4])
vec.min() # Минимальное значение вектора

1

In [47]:
np.max(vec) # Максимальное значение вектора

28

In [49]:
vec.mean() # Среднее значение вектора
# Средним - называют, сумму элементов вектора, поделенную на длинну вектора.

10.75