In [7]:
import numpy as np

np.random.rand() # генерируем случайное число в диапазоне от 0 и до 1.

0.6274073264303115

In [8]:
np.random.rand() * 100 # генерируем случайное число в диапазоне от 0 и до 100.

71.24751591697512

In [9]:
np.random.rand(5) # функция rand() принимает размерность итогового массива, когда передают аргумент.

array([0.91843782, 0.25772915, 0.35189814, 0.76271241, 0.03995184])

In [10]:
np.random.rand(2, 3) # несколько аргументов, создают многомерные массивы.

array([[0.23323832, 0.71731405, 0.14500756],
       [0.67280728, 0.85145562, 0.47191673]])

In [11]:
np.random.rand(2, 3, 4, 10, 12, 23) # создаем шестимерный массив

array([[[[[[3.81929425e-01, 5.27617603e-01, 6.74390695e-01, ...,
            6.39301144e-01, 3.58413087e-02, 1.89106093e-01],
           [7.07977449e-01, 4.16619883e-01, 4.51669544e-01, ...,
            8.67069805e-01, 9.19978015e-01, 9.83875327e-01],
           [4.36019395e-01, 1.47619642e-01, 1.00276317e-01, ...,
            9.29748123e-01, 1.39366205e-01, 4.75655727e-01],
           ...,
           [4.62314587e-01, 5.72857952e-01, 3.57103064e-01, ...,
            8.17946768e-01, 5.01652687e-02, 7.48304563e-01],
           [8.85966809e-01, 8.98896171e-01, 5.95954131e-01, ...,
            9.08095049e-01, 3.63636122e-01, 7.99172271e-01],
           [5.76227380e-01, 7.29496061e-01, 7.64111518e-01, ...,
            2.61222459e-01, 3.27308719e-01, 1.20872715e-01]],

          [[6.97563831e-01, 7.02719493e-01, 1.64176722e-01, ...,
            4.90715529e-02, 3.67300840e-01, 6.35173758e-01],
           [6.05065328e-01, 6.17706474e-01, 4.03487972e-01, ...,
            2.08653069e-01, 7.27696

In [13]:
shape = (3, 4)
np.random.rand(shape) # картеж не может быть интерпритирован как интеджер int.

TypeError: 'tuple' object cannot be interpreted as an integer

In [16]:
shape = (3, 4)
np.random.rand(*shape) # распаковываем картеж и передает в виде аргументов, это не совсем корректный вид.

array([[0.62022959, 0.48838167, 0.34879698, 0.79703574],
       [0.22932458, 0.51618313, 0.95929672, 0.31412433],
       [0.31198506, 0.34198099, 0.99839162, 0.0499922 ]])

In [18]:
shape = (3, 4)
np.random.sample(shape) # но функция Sample как раз и принимает форму массива в виде кортежа.

array([[0.21953447, 0.95720013, 0.21906223, 0.85735438],
       [0.72664681, 0.82070697, 0.19610363, 0.98240244],
       [0.52495705, 0.78528804, 0.54157353, 0.02958936]])

In [19]:
np.random.uniform() # функция юниформ без аргументов генерит случайное число от 0 и до 1.

0.3186221526354226

In [23]:
np.random.uniform(-30, 50) # функция юниформ принимает граничные значения, т.е. значения что нужны для генерации числа. 

42.48862273054311

In [25]:
np.random.uniform(0.5, 0.75, size=5) # с помощью аргумента size можно задавать форму массива в диапазоне,  или одно число

array([0.55041926, 0.59590041, 0.6527232 , 0.58109589, 0.6180699 ])

In [32]:
np.random.uniform(-1000, 500, size=(2, 3)) # с помощью аргумента size можно задавать форму массива в диапазоне, или кортежа
# тут могут быть целые числа и числа с плавующей точкой

array([[  18.70747691, -740.21073994, -368.32445215],
       [-101.9184385 ,  468.43100794, -594.73393798]])

In [35]:
np.random.randint(4, size=(2, 3)) # с помощью randint() можно сгенерировать целые числа. Передавая один аргумент 4(не включая) это создает только верхнюю границу диапазона.

array([[2, 3, 3],
       [0, 2, 1]])

In [37]:
np.random.randint(6, 12, size=(3, 3)) # первый аргумент 6 будет нижний границей диапазона, а 12 верхний(не включая).

array([[ 6,  9,  9],
       [ 7,  8, 11],
       [ 8,  6,  7]])

In [41]:
arr = np.arange(6)
print(arr)
print(np.random.shuffle(arr)) # функция шафл shuffle() перемешивания массива.
arr

[0 1 2 3 4 5]
None


array([0, 5, 1, 3, 4, 2])

In [44]:
playlist = ["The Beatles","Pick Floid","ACDC","Deep Purple","Metalica","RHCP","Slipknot"]

shuffled = np.random.permutation(playlist) # функция permutation() создает новый массив уже перемешанный композиций.
print(shuffled)
print(playlist)

['Deep Purple' 'Pick Floid' 'RHCP' 'ACDC' 'Slipknot' 'Metalica'
 'The Beatles']
['The Beatles', 'Pick Floid', 'ACDC', 'Deep Purple', 'Metalica', 'RHCP', 'Slipknot']


In [45]:
np.random.permutation(10) # передаем число которое будет верхней границей для функции. Если хотите перемешивать числа от и до верхней границы.

array([4, 7, 1, 6, 9, 2, 8, 0, 3, 5])

In [47]:
np.random.choice(5, size=(2, 3)) # функция choice() нужна для работы с разными выборками, она позволяет выбрать из массива данных, какое-то подмножество случайным образом.

array([[1, 4, 2],
       [3, 2, 4]])

In [50]:
workers = ['Ivan','Nikita','Maria','John','Kate','Rassul','Guram','Patima']

choice = np.random.choice(workers, size=2, replace=False) # replace=False - это параметр, для формирования выборки без повторений.
print(choice)

['Rassul' 'John']


In [55]:
workers = ['Ivan','Nikita','Maria','John','Kate','Rassul','Guram','Patima']

choice = np.random.choice(workers, size=10, replace=False) # Задать выборке размерность и без повторений возможны ошибки, если выборка не достаточно велика.
# невозможно получить элементов без повторений больше, чем их доступно изначально.
print(choice)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [58]:
choice = np.random.choice([1, 2, 3, 4, 5, 6], size=10) # тут получает массивы без всяких проблем.
print(choice)

[1 1 3 4 3 4 6 6 4 3]


In [75]:
np.random.seed(23) # начальное число для генерации рандомных чисел функция seed().
np.random.randint(10, size=(3, 4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [79]:
np.random.seed(100)
print(np.random.randint(10, size=(3)))
print(np.random.randint(10, size=(3)))
print(np.random.randint(10, size=(3)))

[8 8 3]
[7 7 0]
[4 2 5]


In [80]:
# seed() должен быть >= 0 и при этом не превосходить 2**32-1. Это правило формирования числа для функции seed().
# seed() число что передают в функцию, должно быть формата unsignedint32() т.е. для числа должно быть выделенно 32 бита памяти и при этом данное число не должно иметь знака.
print(2**32-1)

4294967295
